### ISSUE TITLE
缺少内容

### ISSUE THREAD

**Issue by Liatat** [splpig/cnu_ie#1]
习心事嗲中国特色社会主义思想的创立——
新时代的主要内涵
第一，中国特色社会主义新时代，是承前启后、继往开来、在新的历史条件下继续夺取中国特色社会主义伟大胜利的时代。
这体现的是新时代的历史脉络
改革开放以后，中国特色设会注意建设取得了辉煌成就，为进一步发展奠定了坚实的基础。在新时代，我们将继续紧紧围绕坚持和发展捉个特色社会主义这一主题，分离实现新目标。

**Comment by splpig** [comment]
好了
